language: cpp
os: linux
dist: focal
sudo: false

branches:
  only:
  - master

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_script:
  - sudo apt update -qq
  - sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build libglib2.0-dev libpixman-1-dev
  - git clone https://github.com/riscv/riscv-gnu-toolchain
  - cd riscv-gnu-toolchain
  - mkdir build
  - ./configure --prefix=$(pwd)/build
  - make -j 4 linux
  - export RISCV=$(pwd)/build/bin/

script:
  - make -j 4 CC=$(RISCV)/riscv64-unknown-linux-gnu-gcc AS=$(RISCV)/riscv64-unknown-linux-gnu-as LD=$(RISCV)/riscv64-unknown-linux-gnu-ld

